"""empty message

Revision ID: bec11c36660b
Revises: d310f92bc47f
Create Date: 2024-12-20 05:08:15.203421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec11c36660b'
down_revision = 'd310f92bc47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_index('_genre')
        batch_op.drop_index('_tahun')
        batch_op.create_unique_constraint(None, ['_judul'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('_tahun', ['_tahun'], unique=True)
        batch_op.create_index('_genre', ['_genre'], unique=True)

    # ### end Alembic commands ###
