"""empty message

Revision ID: d310f92bc47f
Revises: 
Create Date: 2024-12-19 19:55:10.976564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd310f92bc47f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bangun',
    sa.Column('bangun_id', sa.Integer(), nullable=False),
    sa.Column('_nama_bangun', sa.String(length=100), nullable=True),
    sa.Column('panjang', sa.Float(), nullable=True),
    sa.Column('lebar', sa.Float(), nullable=True),
    sa.Column('luas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('bangun_id')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_judul', sa.String(length=100), nullable=False),
    sa.Column('_genre', sa.String(length=50), nullable=False),
    sa.Column('_tahun', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_genre'),
    sa.UniqueConstraint('_tahun')
    )
    op.create_table('pesan',
    sa.Column('pesan_id', sa.Integer(), nullable=False),
    sa.Column('_pesan', sa.String(length=300), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pesan_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_nama', sa.String(length=100), nullable=False),
    sa.Column('_alamat', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('pesan')
    op.drop_table('film')
    op.drop_table('bangun')
    # ### end Alembic commands ###
